--CREATE TABLE TODO(
--	TODO_ID INT AUTO_INCREMENT PRIMARY KEY,
--	TODO_NAME VARCHAR(20),
--	TODO_CONTENT VARCHAR(2000),
--	TODO_STATUS CHAR(1),
--	TODO_CREATED_DATE DATE,
--	TODO_START_DATE DATE,
--	TODO_END_DATE DATE
--);

CREATE TABLE todo(
	todo_id INT AUTO_INCREMENT PRIMARY KEY,
	todo_name VARCHAR(20),
	todo_content VARCHAR(2000),
	todo_status CHAR(1),
	todo_created_date DATETIME not null default CURRENT_TIMESTAMP,
	todo_start_date DATETIME not null default CURRENT_TIMESTAMP,
	todo_end_date DATETIME not null default CURRENT_TIMESTAMP
);